apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swagger-ui
spec:
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - name: swagger-ui
        image: swaggerapi/swagger-ui:v3.27.0
        ports:
        - containerPort: 8080
        env:
        - name: URL
          value: https://raw.githubusercontent.com/AstroPlant/astroplant-api/master/openapi.yaml
