apiVersion: v1
kind: Service
metadata:
  name: mosquitto-metrics
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 8000
  selector:
    app: mosquitto
    #app: mqtt-exporter
